### ISSUE TITLE
Add support for Java 8 LocalTime

### ISSUE THREAD

**Issue by briemla** [eXparity/hamcrest-date#15]
Please add support for Java 8 LocalTime in the same way LocalDate is supported.

**Comment by stewbis** [comment]
Hi,

I've just added support for LocalTime and It'll be able in version 2.0.2 which will be available in maven in about and hour. Let me know if it's got the matchers you need.

Thanks

Stewart

**Comment by briemla** [comment]
Hi,

It works like a charm.

Thanks
Lars
