### ISSUE TITLE
Remove or update testng dependency due to errors

### ISSUE THREAD

**Issue by Martin-Wegner** [eXparity/hamcrest-date#18]
Since I updated hamcrest-date from 2.0.2 to 2.0.3 I'm affected by this bug:

https://github.com/cbeust/testng/issues/496

Since hamcrest-date 2.0.3 you have the dependency to testng.
Why?
Can you remove it?

And your dependency version is 6.8.7 from 13.09.2013...
Why?
Can you update it to 6.9.11?

**Comment by stewbis** [comment]
Hi, The test dependency was incorrectly included without test scope. Will create a new release with the pom fixed

**Comment by stewbis** [comment]
Release 2.0.4 is deployed to nexus and will be available in ~ 1 hour.

**Comment by Martin-Wegner** [comment]
:) :+1:
