### ISSUE TITLE
Test assertions (and results) are Locale specific

### ISSUE THREAD

**Issue by tnaskali** [eXparity/hamcrest-date#21]
When I clone the repo and run ```mvn test``` I have multiple Locale-related failures. This is annoying when working on a new feature / fix on a fork.

Example :

```
canDescribeDate(org.exparity.hamcrest.date.core.format.ZonedDateTimeFormatterTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: "Tue, 04 Aug 2015"
     but: was "mar., 04 août 2015"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.exparity.hamcrest.date.core.format.ZonedDateTimeFormatterTest.canDescribeDate(ZonedDateTimeFormatterTest.java:25)
```

**Comment by stewbis** [comment]
All the matchers now support the fluent method atLocale so the Locale used in the matcher errors can be controlled. e.g. 

`assertThat(LocalDate.now(), after(LocalDate.now().minusDays(1)).atLocale(Locale.EN)`
