### ISSUE TITLE
Why no support for OffsetDateTime?

### ISSUE THREAD

**Issue by dalewking** [eXparity/hamcrest-date#24]

**Comment by stewbis** [comment]
Hi dalewking.

Apologies for not getting back sooner and there's no reason for no support of OffsetDateTime, it was just an oversight. I'll add support for OffsetDateTime under this issue.

Regards

Stewart

**Comment by Brutus5000** [comment]
ZonedDateTime would also be nice. I literally discovered your library 5 minutes ago and saw this issue. I see you are working on it. In case you don't have time to add ZonedDateTime I would like take on your OffsetDateTime work and continue it. Just ping me.
Thanks for your effort 👍

**Comment by stewbis** [comment]
Hi @Brutus5000 - many thanks for the offer but ZonedDateTime is already supported under ZonedDateTimeMatchers, I'm actually doing a bit of a code cleanup before adding OffsetDateTime so probably not the best time to jump in - but thanks again

**Comment by stewbis** [comment]
OffsetDateTime support added with OffsetDateMatchers e.g.

`assertThat(OffsetDateTime.now(), OffsetDateMatchers.after(OffsetDateTime.now().minusDays(1)))`
