### ISSUE TITLE
Please use license consistently in the release jar files

### ISSUE THREAD

**Issue by vlsi** [eXparity/hamcrest-date#26]
readme.md says that project license is BSD-3-Clause.

Please propagate that to the release jars, otherwise it is very hard to comply with hamcrest-date license terms.

1) Please add `Bundle-License: BSD-3-Clause` manifest entry (where `BSD-3-Clause` is SPDX identifier, see https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module-bundle-license )
Well, current `pom.xml` tags are quite obvious (even though you might want to replace `<licence><name>` with SPDX id of `BSD-3-Clause`), however adding explicit `Bundle-License` is much more important.

2) Please add LICENSE file to the produced jar file as /META-INF/LICENSE  (and probably to the source repository as /LICENSE).
The thing is the license requires re-distributions to reproduce copyright notice, however it is really hard to do that in an automatic way, taking into account `hamcrest-date.jar` is often taken from Maven Central. The jar file just misses LICENSE file, so it is really hard to reproduce copyright notice and track it for all version upgrades upgrades.

The suggested file locations is `META-INF/LICENSE`

PS I'm implementing an automatic license analysis for Apache JMeter, and I noticed LICENSE is not distributed by hamcrest-date.

**Comment by stewbis** [comment]
This has now been fixed in master and will be release shortly
