### ISSUE TITLE
java.time.Instant support

### ISSUE THREAD

**Issue by ncovercash** [eXparity/hamcrest-date#37]
Heya!

Love this library -- it is super helpful and I am continually surprised Hamcrest itself does not support this functionality.

Are there any plans to support `java.time.Instant`?  It's in the same family as `LocalDateTime` (just has an offset).

**Comment by stewbis** [comment]
Hi,
Thanks for the positive feedback - it's great to know the library is used. Yes, that's an oversight - there's matchers for matching against an Instant, but not Instant against other date info. I'll add one for you. 
Kind regards
Stewart

**Comment by ncovercash** [comment]
Awesome, thank you so much!  It's a wonderful library and I'd be happy to do it myself, I just don't have enough familiarity with the whole hamcrest system quiet yet
