### ISSUE TITLE
Upgrade the hamcrest dependency to version 2.2

### ISSUE THREAD

**Issue by verhasi** [eXparity/hamcrest-date#43]
The current version of hamcrest date is depending on the hamcrest version 1.3. It is old dated and we need to use the newer version as 2.2.

**Comment by verhasi** [comment]
PR created #42

**Comment by minhtran83** [comment]
Hi @verhasi, do you know when we can cut a release including this change? Thanks

**Comment by verhasi** [comment]
Hi @minhtran83!

It is a good question. Actually, I am not a contributor to this project (yet ;) ) so I have no other tools than creating a PR and commenting on it as I did at #42. In the meantime, I suggest you fork the repository and use your own version. If it is valuable for you I can create a release of the forked version under another group id e.g. guru.mocker.hamcrest.

**Comment by verhasi** [comment]
Hi @minhtran83!

I have released today the version 3.0.0 at the [maven central](https://central.sonatype.com/artifact/guru.mocker.hamcrest/hamcrest-date/overview). As I mentioned I have no access to this repository so I have forked it and changed the base package name to guru.mocker. You can find the source code at https://bitbucket.org/mocker-guru/hamcrest-date/src/dev/ along with the README.md. If you have any question feel free to create an issue there.
@stewbis FYI
